! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-3.0.0_gc-AR.alpha2 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Global.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Global

  USE gckpp_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT, LU_NONZERO
  PUBLIC
  SAVE


! Declaration of global variables

! These quantities vary with lon/lat/lev location.
! They must be declared THREADPRIVATE for the parallel
! loop over all cells in the chemistry grid.

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
  !$OMP THREADPRIVATE( C )
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
  !$OMP THREADPRIVATE( VAR )
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
  !$OMP THREADPRIVATE( FIX )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
  !$OMP THREADPRIVATE( RCONST )
! TIME - Current integration time
  REAL(kind=dp) :: TIME
  !$OMP THREADPRIVATE( TIME )
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
  !$OMP THREADPRIVATE( TEMP )
! SR_TEMP - Square root of Temperature [K**0.5]
  REAL(kind=dp) :: SR_TEMP
  !$OMP THREADPRIVATE( SR_TEMP )
! TEMP_OVER_K300 - Temperature [K] / 300.0
  REAL(kind=dp) :: TEMP_OVER_K300
  !$OMP THREADPRIVATE( TEMP_OVER_K300 )
! K300_OVER_TEMP - 300.0 / Temperature [K]
  REAL(kind=dp) :: K300_OVER_TEMP
  !$OMP THREADPRIVATE( K300_OVER_TEMP )
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR
  !$OMP THREADPRIVATE( CFACTOR )
! NUMDEN - Air number density [#/cm3]
  REAL(kind=dp) :: NUMDEN
  !$OMP THREADPRIVATE( NUMDEN )

! These variables do not vary with location, and can be
! assigned outside of the parallel loop over cells in the
! chemistry grid.  These do not need to be THREADPRIVATE.

! MW - Species molecular weight [g/mole]
  REAL(kind=dp) :: MW(NSPEC)
! SR_MW - Square root of species molecular weight [g/mole]
  REAL(kind=dp) :: SR_MW(NSPEC)
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! DO_JVS -
  LOGICAL :: DO_JVS(LU_NONZERO)
! DO_SLV -
  LOGICAL :: DO_SLV(NVAR+1)
! DO_FUN -
  LOGICAL :: DO_FUN(NVAR)
! cLU_IROW -
  INTEGER :: cLU_IROW(LU_NONZERO)
! cLU_ICOL -
  INTEGER :: cLU_ICOL(LU_NONZERO)
! cLU_CROW -
  INTEGER :: cLU_CROW(NVAR+1)
! cLU_DIAG -
  INTEGER :: cLU_DIAG(NVAR+1)
! JVS_MAP -
  INTEGER :: JVS_MAP(LU_NONZERO)
! SPC_MAP -
  INTEGER :: SPC_MAP(NVAR)
! iSPC_MAP -
  INTEGER :: iSPC_MAP(NVAR)
! RMV -
  INTEGER :: RMV(NVAR)
! rNVAR -
  INTEGER :: rNVAR
! cNONZERO -
  INTEGER :: cNONZERO
! KEEPSPCACTIVE -
  LOGICAL :: KEEPSPCACTIVE(NVAR)
! KEEPACTIVE -
  LOGICAL :: KEEPACTIVE
  !$OMP THREADPRIVATE(  DO_JVS, DO_SLV, DO_FUN, cLU_IROW, cLU_ICOL, cLU_CROW )
  !$OMP THREADPRIVATE(  cLU_DIAG, JVS_MAP, SPC_MAP, iSPC_MAP, RMV, rNVAR, cNONZERO, KEEPACTIVE )

! INLINED global variable declarations

      REAL(kind=dp) :: R(NREACT)
!>>      LOGICAL :: DO_JVS(LU_NONZERO)
!>>      LOGICAL :: DO_SLV(NVAR+1)
!>>      LOGICAL :: DO_FUN(NVAR)
!>>      INTEGER :: cLU_IROW(LU_NONZERO)  ! Compacted ROW indexes
!>>      INTEGER :: cLU_ICOL(LU_NONZERO)  ! Compacted COL indexes
!>>      INTEGER :: cLU_CROW(NVAR+1)  ! Compacted compressed row vector
!>>      INTEGER :: cLU_DIAG(NVAR+1)  ! Compacted DIAG indexes
!>>      INTEGER :: JVS_MAP(LU_NONZERO)   ! Map to JVS from compacted sparse datMCRHP
!>>      INTEGER :: SPC_MAP(NVAR)   ! Map species (for Fun(), etc.)
!>>      INTEGER :: rNVAR     ! Compacted number of variable species
!>>      INTEGER :: cNONZERO  ! Compacted number of non-zero elements in cJVS

! INLINED global variable declarations


END MODULE gckpp_Global

