! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-3.0.0-rc.3.flux symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : gckpp_Rates.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Rates

  USE gckpp_Parameters
  USE gckpp_Global
  IMPLICIT NONE
  INTEGER, PARAMETER :: ASSOC = 1, DISSOC = 2

  PRIVATE :: ARR_abc_dp, ARR_abc_sp
  INTERFACE ARR_abc
     MODULE PROCEDURE ARR_abc_dp
     MODULE PROCEDURE ARR_abc_sp
  END INTERFACE ARR_abc

  PRIVATE :: ARR_ab_dp, ARR_ab_sp
  INTERFACE ARR_ab
     MODULE PROCEDURE ARR_ab_dp
     MODULE PROCEDURE ARR_ab_sp
  END INTERFACE ARR_ab

  PRIVATE :: ARR_ac_dp, ARR_ac_sp
  INTERFACE ARR_ac
     MODULE PROCEDURE ARR_ac_dp
     MODULE PROCEDURE ARR_ac_sp
  END INTERFACE ARR_ac

  PRIVATE :: EP2_dp, EP2_sp
  INTERFACE EP2
     MODULE PROCEDURE EP2_dp
     MODULE PROCEDURE EP2_sp
  END INTERFACE EP2

  PRIVATE :: EP3_dp, EP3_sp
  INTERFACE EP3
     MODULE PROCEDURE EP3_dp
     MODULE PROCEDURE EP3_sp
  END INTERFACE EP3

  PRIVATE :: FALL_dp, FALL_sp
  INTERFACE FALL
     MODULE PROCEDURE FALL_dp
     MODULE PROCEDURE FALL_sp
  END INTERFACE FALL

  PRIVATE :: k3rd_jpl_dp, k3rd_jpl_sp
  INTERFACE k3rd_jpl
     MODULE PROCEDURE k3rd_jpl_dp
     MODULE PROCEDURE k3rd_jpl_sp
  END INTERFACE k3rd_jpl

  PRIVATE :: k3rd_jpl_activation_dp, k3rd_jpl_activation_sp
  INTERFACE  k3rd_jpl_activation
     MODULE PROCEDURE  k3rd_jpl_activation_dp
     MODULE PROCEDURE  k3rd_jpl_activation_sp
  END INTERFACE  k3rd_jpl_activation

  PRIVATE :: k3rd_iupac_dp, k3rd_iupac_sp
  INTERFACE k3rd_iupac
     MODULE PROCEDURE k3rd_iupac_dp
     MODULE PROCEDURE k3rd_iupac_sp
  END INTERFACE k3rd_iupac

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!
!  NOTE: For computational efficiency, we have created duplicate rate law
!  routines here that take either all single precision or all double precision
!  arguments.  Explicit casts to DBLE are skipped in the functions that take
!  all double precision arguments (as this removes unneeded computations).
!
!  These functions are overloaded by INTERFACE statements, which are located
!  in file UserRateLawsInterfaces.f90.  The UserRateLawsInterfaces.f90 file
!  will be in-lined into the top of the gckpp_Rates module.
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  FUNCTION ARR_abc_dp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_abc_dp

  FUNCTION ARR_abc_sp( a0, b0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_abc_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ab_dp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (dp args)
    REAL(dp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = a0 * EXP(-b0/TEMP)
  END FUNCTION ARR_ab_dp

  FUNCTION ARR_ab_sp( a0, b0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, b0 (sp args)
    REAL(sp), INTENT(IN) :: a0, b0
    REAL(kind=dp) :: k
    k = DBLE(a0) * EXP(-DBLE(b0)/TEMP)
  END FUNCTION ARR_ab_sp

  !---------------------------------------------------------------------------

  FUNCTION ARR_ac_dp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (dp args)
    REAL(dp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = a0 * (TEMP/300.0_dp)**C0
  END FUNCTION ARR_ac_dp

  FUNCTION ARR_ac_sp( a0, c0 ) RESULT( k )
    ! Arrhenius function, for nonzero a0, c0 (sp args)
    REAL(sp), INTENT(IN) :: a0, c0
    REAL(kind=dp) :: k
    k = DBLE(a0) * (TEMP/300.0_dp)**DBLE(c0)
  END FUNCTION ARR_ac_sp

  !---------------------------------------------------------------------------

  FUNCTION EP2_dp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-c0/temp)
    k2 = a2 * EXP(-c2/temp)
    k3 = a3 * EXP(-c3/temp)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + k3/(1.0_dp + k3/k2)
  END FUNCTION EP2_dp

  FUNCTION EP2_sp( a0, c0, a2, c2, a3, c3 ) RESULT( k )
    ! EP2 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, c0, a2, c2, a3, c3
    REAL(dp) :: k0, k2, k3
    REAL(kind=dp) :: k
    k0 = DBLE(a0) * EXP(-DBLE(c0)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k3 = DBLE(a3) * EXP(-DBLE(c3)/TEMP)
    k3 = k3 * CFACTOR * 1.0E6_dp
    k  = k0 + K3/(1.0_dp + k3/k2)
  END FUNCTION EP2_sp

  !---------------------------------------------------------------------------

  FUNCTION EP3_dp( a1, c1, a2, c2) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = a1 * EXP(-c1/TEMP)
    k2 = a2 * EXP(-c2/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_dp

  FUNCTION EP3_sp( a1, c1, a2, c2 ) RESULT( k )
    ! EP3 function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a1, c1, a2, c2
    REAL(dp) :: k1, k2
    REAL(kind=dp) :: k
    k1 = DBLE(a1) * EXP(-DBLE(c1)/TEMP)
    k2 = DBLE(a2) * EXP(-DBLE(c2)/TEMP)
    k  = k1 + k2*(1.0E6_dp * CFACTOR)
  END FUNCTION EP3_sp

  !---------------------------------------------------------------------------

  FUNCTION FALL_dp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (dp args)
    REAL(dp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = a0 * EXP(-b0/TEMP) * (TEMP/300.0_dp)**c0
    k1 = a1 * EXP(-b1/TEMP) * (TEMP/300.0_dp)**c1
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * cf**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_dp

  FUNCTION FALL_sp( a0, b0, c0, a1, b1, c1, cf ) RESULT( k )
    ! FALL function, for saprc99 and saprcnov (sp args)
    REAL(sp), INTENT(IN) :: a0, b0, c0, a1, b1, c1, cf
    REAL(dp) :: k0, k1
    REAL(kind=dp) :: k
    k0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
    k1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
    k0 = k0 * CFACTOR * 1.0E6_dp
    k1 = k0 / k1
    k  = (k0/(1.0_dp+k1)) * DBLE(cf)**(1.0_dp/(1.0_dp+(LOG10(k1))**2))
  END FUNCTION FALL_sp

  !---------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) three-body reaction formula:
  
  REAL(dp) FUNCTION k3rd_jpl_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(dp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_dp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_dp

  REAL(kind=dp) FUNCTION k3rd_jpl_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL(sp) :: zt_help, k0_T, kinf_T, k_ratio
    zt_help  = 300._dp/temp
    k0_T     = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T   = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio  = k0_T/kinf_T
    k3rd_jpl_sp = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))
  END FUNCTION k3rd_jpl_sp

  ! --------------------------------------------------------------------------

  ! JPL (jpldataeval.jpl.nasa.gov) termolecular chemical activation reaction:

  FUNCTION k3rd_jpl_activation_dp(cair,k0_298K,n,kinf_298K,m,A,B) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), DIMENSION(2) :: k3rd_jpl_activation_dp
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: A         ! for k_int
    REAL(dp), INTENT(IN) :: B         ! for k_int
    REAL(dp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_dp(ASSOC)  = k_f
    k3rd_jpl_activation_dp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_dp

  FUNCTION k3rd_jpl_activation_sp(cair,k0_298K,n,kinf_298K,m,A,B) ! sp args
    INTRINSIC :: LOG10
    REAL(kind=dp), DIMENSION(2) :: k3rd_jpl_activation_sp
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_298K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_298K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: A         ! for k_int
    REAL(sp), INTENT(IN) :: B         ! for k_int
    REAL(sp)             :: zt_help, k0_TM, kinf_T, k_ratio, k_f, k_int, k_fCA
    zt_help = 298./temp
    k0_TM   = k0_298K   * zt_help**n * cair ! k_0   at current T * M
    kinf_T  = kinf_298K * zt_help**m        ! k_inf at current T
    k_ratio = k0_TM/kinf_T
    k_f     = k0_TM/(1.+k_ratio)*0.6**(1./(1.+LOG10(k_ratio)**2))
    k_int   = A * exp(-B/temp)
    k_fCA   = k_int * (1. - k_f/kinf_T)
    k3rd_jpl_activation_sp(ASSOC)  = k_f
    k3rd_jpl_activation_sp(DISSOC) = k_fCA
  END FUNCTION k3rd_jpl_activation_sp

  ! --------------------------------------------------------------------------

  ! IUPAC (iupac.pole-ether.fr) three-body reaction formula:

  REAL(dp) FUNCTION k3rd_iupac_dp(cair,k0_300K,n,kinf_300K,m,fc) ! dp args
    INTRINSIC :: LOG10
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(dp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(dp)             :: nu        ! N
    REAL(dp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_dp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_dp

  REAL(kind=dp) FUNCTION k3rd_iupac_sp(cair,k0_300K,n,kinf_300K,m,fc) ! sp args
    INTRINSIC :: LOG10
    REAL(sp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL(sp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(sp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(sp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(sp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(sp), INTENT(IN) :: fc        ! broadening factor (e.g. 0.45 or 0.6...)
    REAL(sp)             :: nu        ! N
    REAL(sp)             :: zt_help, k0_T, kinf_T, k_ratio
    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    nu      = 0.75-1.27*LOG10(fc)
    k3rd_iupac_sp = k0_T/(1._dp+k_ratio)* &
      fc**(1._dp/(1._dp+(LOG10(k_ratio)/nu)**2))
  END FUNCTION k3rd_iupac_sp

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions


! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
    USE gckpp_Parameters
    USE gckpp_Global

    IMPLICIT NONE

    REAL(kind=dp) :: SunRise, SunSet
    REAL(kind=dp) :: Thour, Tlocal, Ttmp 
    ! PI - Value of pi
    REAL(kind=dp), PARAMETER :: PI = 3.14159265358979d0
    
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (R(1))
  RCONST(2) = (R(2))
  RCONST(3) = (R(3))
  RCONST(4) = (R(4))
  RCONST(5) = (R(5))
  RCONST(6) = (R(6))
  RCONST(7) = (R(7))
  RCONST(8) = (R(8))
  RCONST(9) = (R(9))
  RCONST(10) = (R(10))
  RCONST(11) = (R(11))
  RCONST(12) = (R(12))
  RCONST(13) = (R(13))
  RCONST(14) = (R(14))
  RCONST(15) = (R(15))
  RCONST(16) = (R(16))
  RCONST(17) = (R(17))
  RCONST(18) = (R(18))
  RCONST(19) = (R(19))
  RCONST(20) = (R(20))
  RCONST(21) = (R(21))
  RCONST(22) = (R(22))
  RCONST(23) = (R(23))
  RCONST(24) = (R(24))
  RCONST(25) = (R(25))
  RCONST(26) = (R(26))
  RCONST(27) = (R(27))
  RCONST(28) = (R(28))
  RCONST(29) = (R(29))
  RCONST(30) = (R(30))
  RCONST(31) = (R(31))
  RCONST(32) = (R(32))
  RCONST(33) = (R(33))
  RCONST(34) = (R(34))
  RCONST(35) = (R(35))
  RCONST(36) = (R(36))
  RCONST(37) = (R(37))
  RCONST(38) = (R(38))
  RCONST(39) = (R(39))
  RCONST(40) = (R(40))
  RCONST(41) = (R(41))
  RCONST(42) = (R(42))
  RCONST(43) = (R(43))
  RCONST(44) = (R(44))
  RCONST(45) = (R(45))
  RCONST(46) = (R(46))
  RCONST(47) = (R(47))
  RCONST(48) = (R(48))
  RCONST(49) = (R(49))
  RCONST(50) = (R(50))
  RCONST(51) = (R(51))
  RCONST(52) = (R(52))
  RCONST(53) = (R(53))
  RCONST(54) = (R(54))
  RCONST(55) = (R(55))
  RCONST(56) = (R(56))
  RCONST(57) = (R(57))
  RCONST(58) = (R(58))
  RCONST(59) = (R(59))
  RCONST(60) = (R(60))
  RCONST(61) = (R(61))
  RCONST(62) = (R(62))
  RCONST(63) = (R(63))
  RCONST(64) = (R(64))
  RCONST(65) = (R(65))
  RCONST(66) = (R(66))
  RCONST(67) = (R(67))
  RCONST(68) = (R(68))
  RCONST(69) = (R(69))
  RCONST(70) = (R(70))
  RCONST(71) = (R(71))
  RCONST(72) = (R(72))
  RCONST(73) = (R(73))
  RCONST(74) = (R(74))
  RCONST(75) = (R(75))
  RCONST(76) = (R(76))
  RCONST(77) = (R(77))
  RCONST(78) = (R(78))
  RCONST(79) = (R(79))
  RCONST(80) = (R(80))
  RCONST(81) = (R(81))
  RCONST(82) = (R(82))
  RCONST(83) = (R(83))
  RCONST(84) = (R(84))
  RCONST(85) = (R(85))
  RCONST(86) = (R(86))
  RCONST(87) = (R(87))
  RCONST(88) = (R(88))
  RCONST(89) = (R(89))
  RCONST(90) = (R(90))
  RCONST(91) = (R(91))
  RCONST(92) = (R(92))
  RCONST(93) = (R(93))
  RCONST(94) = (R(94))
  RCONST(95) = (R(95))
  RCONST(96) = (R(96))
  RCONST(97) = (R(97))
  RCONST(98) = (R(98))
  RCONST(99) = (R(99))
  RCONST(100) = (R(100))
  RCONST(101) = (R(101))
  RCONST(102) = (R(102))
  RCONST(103) = (R(103))
  RCONST(104) = (R(104))
  RCONST(105) = (R(105))
  RCONST(106) = (R(106))
  RCONST(107) = (R(107))
  RCONST(108) = (R(108))
  RCONST(109) = (R(109))
  RCONST(110) = (R(110))
  RCONST(111) = (R(111))
  RCONST(112) = (R(112))
  RCONST(113) = (R(113))
  RCONST(114) = (R(114))
  RCONST(115) = (R(115))
  RCONST(116) = (R(116))
  RCONST(117) = (R(117))
  RCONST(118) = (R(118))
  RCONST(119) = (R(119))
  RCONST(120) = (R(120))
  RCONST(121) = (R(121))
  RCONST(122) = (R(122))
  RCONST(123) = (R(123))
  RCONST(124) = (R(124))
  RCONST(125) = (R(125))
  RCONST(126) = (R(126))
  RCONST(127) = (R(127))
  RCONST(128) = (R(128))
  RCONST(129) = (R(129))
  RCONST(130) = (R(130))
  RCONST(131) = (R(131))
  RCONST(132) = (R(132))
  RCONST(133) = (R(133))
  RCONST(134) = (R(134))
  RCONST(135) = (R(135))
  RCONST(136) = (R(136))
  RCONST(137) = (R(137))
  RCONST(138) = (R(138))
  RCONST(139) = (R(139))
  RCONST(140) = (R(140))
  RCONST(141) = (R(141))
  RCONST(142) = (R(142))
  RCONST(143) = (R(143))
  RCONST(144) = (R(144))
  RCONST(145) = (R(145))
  RCONST(146) = (R(146))
  RCONST(147) = (R(147))
  RCONST(148) = (R(148))
  RCONST(149) = (R(149))
  RCONST(150) = (R(150))
  RCONST(151) = (R(151))
  RCONST(152) = (R(152))
  RCONST(153) = (R(153))
  RCONST(154) = (R(154))
  RCONST(155) = (R(155))
  RCONST(156) = (R(156))
  RCONST(157) = (R(157))
  RCONST(158) = (R(158))
  RCONST(159) = (R(159))
  RCONST(160) = (R(160))
  RCONST(161) = (R(161))
  RCONST(162) = (R(162))
  RCONST(163) = (R(163))
  RCONST(164) = (R(164))
  RCONST(165) = (R(165))
  RCONST(166) = (R(166))
  RCONST(167) = (R(167))
  RCONST(168) = (R(168))
  RCONST(169) = (R(169))
  RCONST(170) = (R(170))
  RCONST(171) = (R(171))
  RCONST(172) = (R(172))
  RCONST(173) = (R(173))
  RCONST(174) = (R(174))
  RCONST(175) = (R(175))
  RCONST(176) = (R(176))
  RCONST(177) = (R(177))
  RCONST(178) = (R(178))
  RCONST(179) = (R(179))
  RCONST(180) = (R(180))
  RCONST(181) = (R(181))
  RCONST(182) = (R(182))
  RCONST(183) = (R(183))
  RCONST(184) = (R(184))
  RCONST(185) = (R(185))
  RCONST(186) = (R(186))
  RCONST(187) = (R(187))
  RCONST(188) = (R(188))
  RCONST(189) = (R(189))
  RCONST(190) = (R(190))
  RCONST(191) = (R(191))
  RCONST(192) = (R(192))
  RCONST(193) = (R(193))
  RCONST(194) = (R(194))
  RCONST(195) = (R(195))
  RCONST(196) = (R(196))
  RCONST(197) = (R(197))
  RCONST(198) = (R(198))
  RCONST(199) = (R(199))
  RCONST(200) = (R(200))
  RCONST(201) = (R(201))
  RCONST(202) = (R(202))
  RCONST(203) = (R(203))
  RCONST(204) = (R(204))
  RCONST(205) = (R(205))
  RCONST(206) = (R(206))
  RCONST(207) = (R(207))
  RCONST(208) = (R(208))
  RCONST(209) = (R(209))
  RCONST(210) = (R(210))
  RCONST(211) = (R(211))
  RCONST(212) = (R(212))
  RCONST(213) = (R(213))
  RCONST(214) = (R(214))
  RCONST(215) = (R(215))
  RCONST(216) = (R(216))
  RCONST(217) = (R(217))
  RCONST(218) = (R(218))
  RCONST(219) = (R(219))
  RCONST(220) = (R(220))
  RCONST(221) = (R(221))
  RCONST(222) = (R(222))
  RCONST(223) = (R(223))
  RCONST(224) = (R(224))
  RCONST(225) = (R(225))
  RCONST(226) = (R(226))
  RCONST(227) = (R(227))
  RCONST(228) = (R(228))
  RCONST(229) = (R(229))
  RCONST(230) = (R(230))
  RCONST(231) = (R(231))
  RCONST(232) = (R(232))
  RCONST(233) = (R(233))
  RCONST(234) = (R(234))
  RCONST(235) = (R(235))
  RCONST(236) = (R(236))
  RCONST(237) = (R(237))
  RCONST(238) = (R(238))
  RCONST(239) = (R(239))
  RCONST(240) = (R(240))
  RCONST(241) = (R(241))
  RCONST(242) = (R(242))
  RCONST(243) = (R(243))
  RCONST(244) = (R(244))
  RCONST(245) = (R(245))
  RCONST(246) = (R(246))
  RCONST(247) = (R(247))
  RCONST(248) = (R(248))
  RCONST(249) = (R(249))
  RCONST(250) = (R(250))
  RCONST(251) = (R(251))
  RCONST(252) = (R(252))
  RCONST(253) = (R(253))
  RCONST(254) = (R(254))
  RCONST(255) = (R(255))
  RCONST(256) = (R(256))
  RCONST(257) = (R(257))
  RCONST(258) = (R(258))
  RCONST(259) = (R(259))
  RCONST(260) = (R(260))
  RCONST(261) = (R(261))
  RCONST(262) = (R(262))
  RCONST(263) = (R(263))
  RCONST(264) = (R(264))
  RCONST(265) = (R(265))
  RCONST(266) = (R(266))
  RCONST(267) = (R(267))
  RCONST(268) = (R(268))
  RCONST(269) = (R(269))
  RCONST(270) = (R(270))
  RCONST(271) = (R(271))
  RCONST(272) = (R(272))
  RCONST(273) = (R(273))
  RCONST(274) = (R(274))
  RCONST(275) = (R(275))
  RCONST(276) = (R(276))
  RCONST(277) = (R(277))
  RCONST(278) = (R(278))
  RCONST(279) = (R(279))
  RCONST(280) = (R(280))
  RCONST(281) = (R(281))
  RCONST(282) = (R(282))
  RCONST(283) = (R(283))
  RCONST(284) = (R(284))
  RCONST(285) = (R(285))
  RCONST(286) = (R(286))
  RCONST(287) = (R(287))
  RCONST(288) = (R(288))
  RCONST(289) = (R(289))
  RCONST(290) = (R(290))
  RCONST(291) = (R(291))
  RCONST(292) = (R(292))
  RCONST(293) = (R(293))
  RCONST(294) = (R(294))
  RCONST(295) = (R(295))
  RCONST(296) = (R(296))
  RCONST(297) = (R(297))
  RCONST(298) = (R(298))
  RCONST(299) = (R(299))
  RCONST(300) = (R(300))
  RCONST(301) = (R(301))
  RCONST(302) = (R(302))
  RCONST(303) = (R(303))
  RCONST(304) = (R(304))
  RCONST(305) = (R(305))
  RCONST(306) = (R(306))
  RCONST(307) = (R(307))
  RCONST(308) = (R(308))
  RCONST(309) = (R(309))
  RCONST(310) = (R(310))
  RCONST(311) = (R(311))
  RCONST(312) = (R(312))
  RCONST(313) = (R(313))
  RCONST(314) = (R(314))
  RCONST(315) = (R(315))
  RCONST(316) = (R(316))
  RCONST(317) = (R(317))
  RCONST(318) = (R(318))
  RCONST(319) = (R(319))
  RCONST(320) = (R(320))
  RCONST(321) = (R(321))
  RCONST(322) = (R(322))
  RCONST(323) = (R(323))
  RCONST(324) = (R(324))
  RCONST(325) = (R(325))
  RCONST(326) = (R(326))
  RCONST(327) = (R(327))
  RCONST(328) = (R(328))
  RCONST(329) = (R(329))
  RCONST(330) = (R(330))
  RCONST(331) = (R(331))
  RCONST(332) = (R(332))
  RCONST(333) = (R(333))
  RCONST(334) = (R(334))
  RCONST(335) = (R(335))
  RCONST(336) = (R(336))
  RCONST(337) = (R(337))
  RCONST(338) = (R(338))
  RCONST(339) = (R(339))
  RCONST(340) = (R(340))
  RCONST(341) = (R(341))
  RCONST(342) = (R(342))
  RCONST(343) = (R(343))
  RCONST(344) = (R(344))
  RCONST(345) = (R(345))
  RCONST(346) = (R(346))
  RCONST(347) = (R(347))
  RCONST(348) = (R(348))
  RCONST(349) = (R(349))
  RCONST(350) = (R(350))
  RCONST(351) = (R(351))
  RCONST(352) = (R(352))
  RCONST(353) = (R(353))
  RCONST(354) = (R(354))
  RCONST(355) = (R(355))
  RCONST(356) = (R(356))
  RCONST(357) = (R(357))
  RCONST(358) = (R(358))
  RCONST(359) = (R(359))
  RCONST(360) = (R(360))
  RCONST(361) = (R(361))
  RCONST(362) = (R(362))
  RCONST(363) = (R(363))
  RCONST(364) = (R(364))
  RCONST(365) = (R(365))
  RCONST(366) = (R(366))
  RCONST(367) = (R(367))
  RCONST(368) = (R(368))
  RCONST(369) = (R(369))
  RCONST(370) = (R(370))
  RCONST(371) = (R(371))
  RCONST(372) = (R(372))
  RCONST(373) = (R(373))
  RCONST(374) = (R(374))
  RCONST(375) = (R(375))
  RCONST(376) = (R(376))
  RCONST(377) = (R(377))
  RCONST(378) = (R(378))
  RCONST(379) = (R(379))
  RCONST(380) = (R(380))
  RCONST(381) = (R(381))
  RCONST(382) = (R(382))
  RCONST(383) = (R(383))
  RCONST(384) = (R(384))
  RCONST(385) = (R(385))
  RCONST(386) = (R(386))
  RCONST(387) = (R(387))
  RCONST(388) = (R(388))
  RCONST(389) = (R(389))
  RCONST(390) = (R(390))
  RCONST(391) = (R(391))
  RCONST(392) = (R(392))
  RCONST(393) = (R(393))
  RCONST(394) = (R(394))
  RCONST(395) = (R(395))
  RCONST(396) = (R(396))
  RCONST(397) = (R(397))
  RCONST(398) = (R(398))
  RCONST(399) = (R(399))
  RCONST(400) = (R(400))
  RCONST(401) = (R(401))
  RCONST(402) = (R(402))
  RCONST(403) = (R(403))
  RCONST(404) = (R(404))
  RCONST(405) = (R(405))
  RCONST(406) = (R(406))
  RCONST(407) = (R(407))
  RCONST(408) = (R(408))
  RCONST(409) = (R(409))
  RCONST(410) = (R(410))
  RCONST(411) = (R(411))
  RCONST(412) = (R(412))
  RCONST(413) = (R(413))
  RCONST(414) = (R(414))
  RCONST(415) = (R(415))
  RCONST(416) = (R(416))
  RCONST(417) = (R(417))
  RCONST(418) = (R(418))
  RCONST(419) = (R(419))
  RCONST(420) = (R(420))
  RCONST(421) = (R(421))
  RCONST(422) = (R(422))
  RCONST(423) = (R(423))
  RCONST(424) = (R(424))
  RCONST(425) = (R(425))
  RCONST(426) = (R(426))
  RCONST(427) = (R(427))
  RCONST(428) = (R(428))
  RCONST(429) = (R(429))
  RCONST(430) = (R(430))
  RCONST(431) = (R(431))
  RCONST(432) = (R(432))
  RCONST(433) = (R(433))
  RCONST(434) = (R(434))
  RCONST(435) = (R(435))
  RCONST(436) = (R(436))
  RCONST(437) = (R(437))
  RCONST(438) = (R(438))
  RCONST(439) = (R(439))
  RCONST(440) = (R(440))
  RCONST(441) = (R(441))
  RCONST(442) = (R(442))
  RCONST(443) = (R(443))
  RCONST(444) = (R(444))
  RCONST(445) = (R(445))
  RCONST(446) = (R(446))
  RCONST(447) = (R(447))
  RCONST(448) = (R(448))
  RCONST(449) = (R(449))
  RCONST(450) = (R(450))
  RCONST(451) = (R(451))
  RCONST(452) = (R(452))
  RCONST(453) = (R(453))
  RCONST(454) = (R(454))
  RCONST(455) = (R(455))
  RCONST(456) = (R(456))
  RCONST(457) = (R(457))
  RCONST(458) = (R(458))
  RCONST(459) = (R(459))
  RCONST(460) = (R(460))
  RCONST(461) = (R(461))
  RCONST(462) = (R(462))
  RCONST(463) = (R(463))
  RCONST(464) = (R(464))
  RCONST(465) = (R(465))
  RCONST(466) = (R(466))
  RCONST(467) = (R(467))
  RCONST(468) = (R(468))
  RCONST(469) = (R(469))
  RCONST(470) = (R(470))
  RCONST(471) = (R(471))
  RCONST(472) = (R(472))
  RCONST(473) = (R(473))
  RCONST(474) = (R(474))
  RCONST(475) = (R(475))
  RCONST(476) = (R(476))
  RCONST(477) = (R(477))
  RCONST(478) = (R(478))
  RCONST(479) = (R(479))
  RCONST(480) = (R(480))
  RCONST(481) = (R(481))
  RCONST(482) = (R(482))
  RCONST(483) = (R(483))
  RCONST(484) = (R(484))
  RCONST(485) = (R(485))
  RCONST(486) = (R(486))
  RCONST(487) = (R(487))
  RCONST(488) = (R(488))
  RCONST(489) = (R(489))
  RCONST(490) = (R(490))
  RCONST(491) = (R(491))
  RCONST(492) = (R(492))
  RCONST(493) = (R(493))
  RCONST(494) = (R(494))
  RCONST(495) = (R(495))
  RCONST(496) = (R(496))
  RCONST(497) = (R(497))
  RCONST(498) = (R(498))
  RCONST(499) = (R(499))
  RCONST(500) = (R(500))
  RCONST(501) = (R(501))
  RCONST(502) = (R(502))
  RCONST(503) = (R(503))
  RCONST(504) = (R(504))
  RCONST(505) = (R(505))
  RCONST(506) = (R(506))
  RCONST(507) = (R(507))
  RCONST(508) = (R(508))
  RCONST(509) = (R(509))
  RCONST(510) = (R(510))
  RCONST(511) = (R(511))
  RCONST(512) = (R(512))
  RCONST(513) = (R(513))
  RCONST(514) = (R(514))
  RCONST(515) = (R(515))
  RCONST(516) = (R(516))
  RCONST(517) = (R(517))
  RCONST(518) = (R(518))
  RCONST(519) = (R(519))
  RCONST(520) = (R(520))
  RCONST(521) = (R(521))
  RCONST(522) = (R(522))
  RCONST(523) = (R(523))
  RCONST(524) = (R(524))
  RCONST(525) = (R(525))
  RCONST(526) = (R(526))
  RCONST(527) = (R(527))
  RCONST(528) = (R(528))
  RCONST(529) = (R(529))
  RCONST(530) = (R(530))
  RCONST(531) = (R(531))
  RCONST(532) = (R(532))
  RCONST(533) = (R(533))
  RCONST(534) = (R(534))
  RCONST(535) = (R(535))
  RCONST(536) = (R(536))
  RCONST(537) = (R(537))
  RCONST(538) = (R(538))
  RCONST(539) = (R(539))
  RCONST(540) = (R(540))
  RCONST(541) = (R(541))
  RCONST(542) = (R(542))
  RCONST(543) = (R(543))
  RCONST(544) = (R(544))
  RCONST(545) = (R(545))
  RCONST(546) = (R(546))
  RCONST(547) = (R(547))
  RCONST(548) = (R(548))
  RCONST(549) = (R(549))
  RCONST(550) = (R(550))
  RCONST(551) = (R(551))
  RCONST(552) = (R(552))
  RCONST(553) = (R(553))
  RCONST(554) = (R(554))
  RCONST(555) = (R(555))
  RCONST(556) = (R(556))
  RCONST(557) = (R(557))
  RCONST(558) = (R(558))
  RCONST(559) = (R(559))
  RCONST(560) = (R(560))
  RCONST(561) = (R(561))
  RCONST(562) = (R(562))
  RCONST(563) = (R(563))
  RCONST(564) = (R(564))
  RCONST(565) = (R(565))
  RCONST(566) = (R(566))
  RCONST(567) = (R(567))
  RCONST(568) = (R(568))
  RCONST(569) = (R(569))
  RCONST(570) = (R(570))
  RCONST(571) = (R(571))
  RCONST(572) = (R(572))
  RCONST(573) = (R(573))
  RCONST(574) = (R(574))
  RCONST(575) = (R(575))
  RCONST(576) = (R(576))
  RCONST(577) = (R(577))
  RCONST(578) = (R(578))
  RCONST(579) = (R(579))
  RCONST(580) = (R(580))
  RCONST(581) = (R(581))
  RCONST(582) = (R(582))
  RCONST(583) = (R(583))
  RCONST(584) = (R(584))
  RCONST(585) = (R(585))
  RCONST(586) = (R(586))
  RCONST(587) = (R(587))
  RCONST(588) = (R(588))
  RCONST(589) = (R(589))
  RCONST(590) = (R(590))
  RCONST(591) = (R(591))
  RCONST(592) = (R(592))
  RCONST(593) = (R(593))
  RCONST(594) = (R(594))
  RCONST(595) = (R(595))
  RCONST(596) = (R(596))
  RCONST(597) = (R(597))
  RCONST(598) = (R(598))
  RCONST(599) = (R(599))
  RCONST(600) = (R(600))
  RCONST(601) = (R(601))
  RCONST(602) = (R(602))
  RCONST(603) = (R(603))
  RCONST(604) = (R(604))
  RCONST(605) = (R(605))
  RCONST(606) = (R(606))
  RCONST(607) = (R(607))
  RCONST(608) = (R(608))
  RCONST(609) = (R(609))
  RCONST(610) = (R(610))
  RCONST(611) = (R(611))
  RCONST(612) = (R(612))
  RCONST(613) = (R(613))
  RCONST(614) = (R(614))
  RCONST(615) = (R(615))
  RCONST(616) = (R(616))
  RCONST(617) = (R(617))
  RCONST(618) = (R(618))
  RCONST(619) = (R(619))
  RCONST(620) = (R(620))
  RCONST(621) = (R(621))
  RCONST(622) = (R(622))
  RCONST(623) = (R(623))
  RCONST(624) = (R(624))
  RCONST(625) = (R(625))
  RCONST(626) = (R(626))
  RCONST(627) = (R(627))
  RCONST(628) = (R(628))
  RCONST(629) = (R(629))
  RCONST(630) = (R(630))
  RCONST(631) = (R(631))
  RCONST(632) = (R(632))
  RCONST(633) = (R(633))
  RCONST(634) = (R(634))
  RCONST(635) = (R(635))
  RCONST(636) = (R(636))
  RCONST(637) = (R(637))
  RCONST(638) = (R(638))
  RCONST(639) = (R(639))
  RCONST(640) = (R(640))
  RCONST(641) = (R(641))
  RCONST(642) = (R(642))
  RCONST(643) = (R(643))
  RCONST(644) = (R(644))
  RCONST(645) = (R(645))
  RCONST(646) = (R(646))
  RCONST(647) = (R(647))
  RCONST(648) = (R(648))
  RCONST(649) = (R(649))
  RCONST(650) = (R(650))
  RCONST(651) = (R(651))
  RCONST(652) = (R(652))
  RCONST(653) = (R(653))
  RCONST(654) = (R(654))
  RCONST(655) = (R(655))
  RCONST(656) = (R(656))
  RCONST(657) = (R(657))
  RCONST(658) = (R(658))
  RCONST(659) = (R(659))
  RCONST(660) = (R(660))
  RCONST(661) = (R(661))
  RCONST(662) = (R(662))
  RCONST(663) = (R(663))
  RCONST(664) = (R(664))
  RCONST(665) = (R(665))
  RCONST(666) = (R(666))
  RCONST(667) = (R(667))
  RCONST(668) = (R(668))
  RCONST(669) = (R(669))
  RCONST(670) = (R(670))
  RCONST(671) = (R(671))
  RCONST(672) = (R(672))
  RCONST(673) = (R(673))
  RCONST(674) = (R(674))
  RCONST(675) = (R(675))
  RCONST(676) = (R(676))
  RCONST(677) = (R(677))
  RCONST(678) = (R(678))
  RCONST(679) = (R(679))
  RCONST(680) = (R(680))
  RCONST(681) = (R(681))
  RCONST(682) = (R(682))
  RCONST(683) = (R(683))
  RCONST(684) = (R(684))
  RCONST(685) = (R(685))
  RCONST(686) = (R(686))
  RCONST(687) = (R(687))
  RCONST(688) = (R(688))
  RCONST(689) = (R(689))
  RCONST(690) = (R(690))
  RCONST(691) = (R(691))
  RCONST(692) = (R(692))
  RCONST(693) = (R(693))
  RCONST(694) = (R(694))
  RCONST(695) = (R(695))
  RCONST(696) = (R(696))
  RCONST(697) = (R(697))
  RCONST(698) = (R(698))
  RCONST(699) = (R(699))
  RCONST(700) = (R(700))
  RCONST(701) = (R(701))
  RCONST(702) = (R(702))
  RCONST(703) = (R(703))
  RCONST(704) = (R(704))
  RCONST(705) = (R(705))
  RCONST(706) = (R(706))
  RCONST(707) = (R(707))
  RCONST(708) = (R(708))
  RCONST(709) = (R(709))
  RCONST(710) = (R(710))
  RCONST(711) = (R(711))
  RCONST(712) = (R(712))
  RCONST(713) = (R(713))
  RCONST(714) = (R(714))
  RCONST(715) = (R(715))
  RCONST(716) = (R(716))
  RCONST(717) = (R(717))
  RCONST(718) = (R(718))
  RCONST(719) = (R(719))
  RCONST(720) = (R(720))
  RCONST(721) = (R(721))
  RCONST(722) = (R(722))
  RCONST(723) = (R(723))
  RCONST(724) = (R(724))
  RCONST(725) = (R(725))
  RCONST(726) = (R(726))
  RCONST(727) = (R(727))
  RCONST(728) = (R(728))
  RCONST(729) = (R(729))
  RCONST(730) = (R(730))
  RCONST(731) = (R(731))
  RCONST(732) = (R(732))
  RCONST(733) = (R(733))
  RCONST(734) = (R(734))
  RCONST(735) = (R(735))
  RCONST(736) = (R(736))
  RCONST(737) = (R(737))
  RCONST(738) = (R(738))
  RCONST(739) = (R(739))
  RCONST(740) = (R(740))
  RCONST(741) = (R(741))
  RCONST(742) = (R(742))
  RCONST(743) = (R(743))
  RCONST(744) = (R(744))
  RCONST(745) = (R(745))
  RCONST(746) = (R(746))
  RCONST(747) = (R(747))
  RCONST(748) = (R(748))
  RCONST(749) = (R(749))
  RCONST(750) = (R(750))
  RCONST(751) = (R(751))
  RCONST(752) = (R(752))
  RCONST(753) = (R(753))
  RCONST(754) = (R(754))
  RCONST(755) = (R(755))
  RCONST(756) = (R(756))
  RCONST(757) = (R(757))
  RCONST(758) = (R(758))
  RCONST(759) = (R(759))
  RCONST(760) = (R(760))
  RCONST(761) = (R(761))
  RCONST(762) = (R(762))
  RCONST(763) = (R(763))
  RCONST(764) = (R(764))
  RCONST(765) = (R(765))
  RCONST(766) = (R(766))
  RCONST(767) = (R(767))
  RCONST(768) = (R(768))
  RCONST(769) = (R(769))
  RCONST(770) = (R(770))
  RCONST(771) = (R(771))
  RCONST(772) = (R(772))
  RCONST(773) = (R(773))
  RCONST(774) = (R(774))
  RCONST(775) = (R(775))
  RCONST(776) = (R(776))
  RCONST(777) = (R(777))
  RCONST(778) = (R(778))
  RCONST(779) = (R(779))
  RCONST(780) = (R(780))
  RCONST(781) = (R(781))
  RCONST(782) = (R(782))
  RCONST(783) = (R(783))
  RCONST(784) = (R(784))
  RCONST(785) = (R(785))
  RCONST(786) = (R(786))
  RCONST(787) = (R(787))
  RCONST(788) = (R(788))
  RCONST(789) = (R(789))
  RCONST(790) = (R(790))
  RCONST(791) = (R(791))
  RCONST(792) = (R(792))
  RCONST(793) = (R(793))
  RCONST(794) = (R(794))
  RCONST(795) = (R(795))
  RCONST(796) = (R(796))
  RCONST(797) = (R(797))
  RCONST(798) = (R(798))
  RCONST(799) = (R(799))
  RCONST(800) = (R(800))
  RCONST(801) = (R(801))
  RCONST(802) = (R(802))
  RCONST(803) = (R(803))
  RCONST(804) = (R(804))
  RCONST(805) = (R(805))
  RCONST(806) = (R(806))
  RCONST(807) = (R(807))
  RCONST(808) = (R(808))
  RCONST(809) = (R(809))
  RCONST(810) = (R(810))
  RCONST(811) = (R(811))
  RCONST(812) = (R(812))
  RCONST(813) = (R(813))
  RCONST(814) = (R(814))
  RCONST(815) = (R(815))
  RCONST(816) = (R(816))
  RCONST(817) = (R(817))
  RCONST(818) = (R(818))
  RCONST(819) = (R(819))
  RCONST(820) = (R(820))
  RCONST(821) = (R(821))
  RCONST(822) = (R(822))
  RCONST(823) = (R(823))
  RCONST(824) = (R(824))
  RCONST(825) = (R(825))
  RCONST(826) = (R(826))
  RCONST(827) = (R(827))
  RCONST(828) = (R(828))
  RCONST(829) = (R(829))
  RCONST(830) = (R(830))
  RCONST(831) = (R(831))
  RCONST(832) = (R(832))
  RCONST(833) = (R(833))
  RCONST(834) = (R(834))
  RCONST(835) = (R(835))
  RCONST(836) = (R(836))
  RCONST(837) = (R(837))
  RCONST(838) = (R(838))
  RCONST(839) = (R(839))
  RCONST(840) = (R(840))
  RCONST(841) = (R(841))
  RCONST(842) = (R(842))
  RCONST(843) = (R(843))
  RCONST(844) = (R(844))
  RCONST(845) = (R(845))
  RCONST(846) = (R(846))
  RCONST(847) = (R(847))
  RCONST(848) = (R(848))
  RCONST(849) = (R(849))
  RCONST(850) = (R(850))
  RCONST(851) = (R(851))
  RCONST(852) = (R(852))
  RCONST(853) = (R(853))
  RCONST(854) = (R(854))
  RCONST(855) = (R(855))
  RCONST(856) = (R(856))
  RCONST(857) = (R(857))
  RCONST(858) = (R(858))
  RCONST(859) = (R(859))
  RCONST(860) = (R(860))
  RCONST(861) = (R(861))
  RCONST(862) = (R(862))
  RCONST(863) = (R(863))
  RCONST(864) = (R(864))
  RCONST(865) = (R(865))
  RCONST(866) = (R(866))
  RCONST(867) = (R(867))
  RCONST(868) = (R(868))
  RCONST(869) = (R(869))
  RCONST(870) = (R(870))
  RCONST(871) = (R(871))
  RCONST(872) = (R(872))
  RCONST(873) = (R(873))
  RCONST(874) = (R(874))
  RCONST(875) = (R(875))
  RCONST(876) = (R(876))
  RCONST(877) = (R(877))
  RCONST(878) = (R(878))
  RCONST(879) = (R(879))
  RCONST(880) = (R(880))
  RCONST(881) = (R(881))
  RCONST(882) = (R(882))
  RCONST(883) = (R(883))
  RCONST(884) = (R(884))
  RCONST(885) = (R(885))
  RCONST(886) = (R(886))
  RCONST(887) = (R(887))
  RCONST(888) = (R(888))
  RCONST(889) = (R(889))
  RCONST(890) = (R(890))
  RCONST(891) = (R(891))
  RCONST(892) = (R(892))
  RCONST(893) = (R(893))
  RCONST(894) = (R(894))
  RCONST(895) = (R(895))
  RCONST(896) = (R(896))
  RCONST(897) = (R(897))
  RCONST(898) = (R(898))
  RCONST(899) = (R(899))
  RCONST(900) = (R(900))
  RCONST(901) = (R(901))
  RCONST(902) = (R(902))
  RCONST(903) = (R(903))
  RCONST(904) = (R(904))
  RCONST(905) = (R(905))
  RCONST(906) = (R(906))
  RCONST(907) = (R(907))
  RCONST(908) = (R(908))
  RCONST(909) = (R(909))
  RCONST(910) = (R(910))
  RCONST(911) = (R(911))
  RCONST(912) = (R(912))
  RCONST(913) = (R(913))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )



! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(757) = (R(757))
  RCONST(758) = (R(758))
  RCONST(759) = (R(759))
  RCONST(760) = (R(760))
  RCONST(761) = (R(761))
  RCONST(762) = (R(762))
  RCONST(763) = (R(763))
  RCONST(764) = (R(764))
  RCONST(765) = (R(765))
  RCONST(766) = (R(766))
  RCONST(767) = (R(767))
  RCONST(768) = (R(768))
  RCONST(769) = (R(769))
  RCONST(770) = (R(770))
  RCONST(771) = (R(771))
  RCONST(772) = (R(772))
  RCONST(773) = (R(773))
  RCONST(774) = (R(774))
  RCONST(775) = (R(775))
  RCONST(776) = (R(776))
  RCONST(777) = (R(777))
  RCONST(778) = (R(778))
  RCONST(779) = (R(779))
  RCONST(780) = (R(780))
  RCONST(781) = (R(781))
  RCONST(782) = (R(782))
  RCONST(783) = (R(783))
  RCONST(784) = (R(784))
  RCONST(785) = (R(785))
  RCONST(786) = (R(786))
  RCONST(787) = (R(787))
  RCONST(788) = (R(788))
  RCONST(789) = (R(789))
  RCONST(790) = (R(790))
  RCONST(791) = (R(791))
  RCONST(792) = (R(792))
  RCONST(793) = (R(793))
  RCONST(794) = (R(794))
  RCONST(795) = (R(795))
  RCONST(796) = (R(796))
  RCONST(797) = (R(797))
  RCONST(798) = (R(798))
  RCONST(799) = (R(799))
  RCONST(800) = (R(800))
  RCONST(801) = (R(801))
  RCONST(802) = (R(802))
  RCONST(803) = (R(803))
  RCONST(804) = (R(804))
  RCONST(805) = (R(805))
  RCONST(806) = (R(806))
  RCONST(807) = (R(807))
  RCONST(808) = (R(808))
  RCONST(809) = (R(809))
  RCONST(810) = (R(810))
  RCONST(811) = (R(811))
  RCONST(812) = (R(812))
  RCONST(813) = (R(813))
  RCONST(814) = (R(814))
  RCONST(815) = (R(815))
  RCONST(816) = (R(816))
  RCONST(817) = (R(817))
  RCONST(818) = (R(818))
  RCONST(819) = (R(819))
  RCONST(820) = (R(820))
  RCONST(821) = (R(821))
  RCONST(822) = (R(822))
  RCONST(823) = (R(823))
  RCONST(824) = (R(824))
  RCONST(825) = (R(825))
  RCONST(826) = (R(826))
  RCONST(827) = (R(827))
  RCONST(828) = (R(828))
  RCONST(829) = (R(829))
  RCONST(830) = (R(830))
  RCONST(831) = (R(831))
  RCONST(832) = (R(832))
  RCONST(833) = (R(833))
  RCONST(834) = (R(834))
  RCONST(835) = (R(835))
  RCONST(836) = (R(836))
  RCONST(837) = (R(837))
  RCONST(838) = (R(838))
  RCONST(839) = (R(839))
  RCONST(840) = (R(840))
  RCONST(841) = (R(841))
  RCONST(842) = (R(842))
  RCONST(843) = (R(843))
  RCONST(844) = (R(844))
  RCONST(845) = (R(845))
  RCONST(846) = (R(846))
  RCONST(847) = (R(847))
  RCONST(848) = (R(848))
  RCONST(849) = (R(849))
  RCONST(850) = (R(850))
  RCONST(851) = (R(851))
  RCONST(852) = (R(852))
  RCONST(853) = (R(853))
  RCONST(854) = (R(854))
  RCONST(855) = (R(855))
  RCONST(856) = (R(856))
  RCONST(857) = (R(857))
  RCONST(858) = (R(858))
  RCONST(859) = (R(859))
  RCONST(860) = (R(860))
  RCONST(861) = (R(861))
  RCONST(862) = (R(862))
  RCONST(863) = (R(863))
  RCONST(864) = (R(864))
  RCONST(865) = (R(865))
  RCONST(866) = (R(866))
  RCONST(867) = (R(867))
  RCONST(868) = (R(868))
  RCONST(869) = (R(869))
  RCONST(870) = (R(870))
  RCONST(871) = (R(871))
  RCONST(872) = (R(872))
  RCONST(873) = (R(873))
  RCONST(874) = (R(874))
  RCONST(875) = (R(875))
  RCONST(876) = (R(876))
  RCONST(877) = (R(877))
  RCONST(878) = (R(878))
  RCONST(879) = (R(879))
  RCONST(880) = (R(880))
  RCONST(881) = (R(881))
  RCONST(882) = (R(882))
  RCONST(883) = (R(883))
  RCONST(884) = (R(884))
  RCONST(885) = (R(885))
  RCONST(886) = (R(886))
  RCONST(887) = (R(887))
  RCONST(888) = (R(888))
  RCONST(889) = (R(889))
  RCONST(890) = (R(890))
  RCONST(891) = (R(891))
  RCONST(892) = (R(892))
  RCONST(893) = (R(893))
  RCONST(894) = (R(894))
  RCONST(895) = (R(895))
  RCONST(896) = (R(896))
  RCONST(897) = (R(897))
  RCONST(898) = (R(898))
  RCONST(899) = (R(899))
  RCONST(900) = (R(900))
  RCONST(901) = (R(901))
  RCONST(902) = (R(902))
  RCONST(903) = (R(903))
  RCONST(904) = (R(904))
  RCONST(905) = (R(905))
  RCONST(906) = (R(906))
  RCONST(907) = (R(907))
  RCONST(908) = (R(908))
  RCONST(909) = (R(909))
  RCONST(910) = (R(910))
  RCONST(911) = (R(911))
  RCONST(912) = (R(912))
  RCONST(913) = (R(913))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Rates

