PROGRAM Main
  !
  ! The KPP Standalone for GEOS-Chem Mechanism Analysis
  !
  !
  ! Program Description:
  !
  ! This program runs the GEOS-Chem KPP Standalone for a given set of initial
  ! conditions.  It reads an input file generated by the KPP Standalone
  ! Interface that generates model output of the full chemical state of grid
  ! cells in 3D GEOS-Chem, GCHP, and GEOS-CF runs.  The full mechanism is
  ! run to read (*,*) plicate the chemistry of the specified grid cell.
  !
  ! Obin Sturm (psturm@usc.edu), Michael S Long, Christoph Keller
  !
  ! The KPP Standalone is adapted from a box model used in the following
  ! publication:
  !
  !    Lin, H., Long, M. S., Sander, R., Sandu, A., Yantosca, R. M., Estrada,
  !    L. A., et al. (2023). "An adaptive auto-reduction solver for speeding
  !    up integration of chemical kinetics in atmospheric chemistry models:
  !    Implementation and evaluation in the Kinetic Pre-Processor (KPP)
  !    version 3.0.0.", Journal of Advances in Modeling Earth Systems, 15,
  !    e2022MS003293. https://doi.org/10.1029/2022MS003293
  !
  ! Updates:
  !  - 2024/05/06, Obin Sturm: Simplification of the code for the GEOS-Chem
  !                            KPP Standalone, removed all autoreduce and
  !                            convergence criteria testing.  The more general
  !                            tool just runs one operator timestep and then
  !                            prints out the results to an output file.
  !
  USE GCKPP_GLOBAL
  USE GCKPP_JACOBIANSP
  USE GCKPP_PARAMETERS
  USE GCKPP_MONITOR
  USE GCKPP_MODEL
  USE KPP_STANDALONE_INIT, ONLY: read_input

  IMPLICIT NONE

  ! Scalars
  INTEGER            :: nArgs
  INTEGER            :: IERR
  INTEGER            :: fileTotSteps
  INTEGER            :: level
  REAL(dp)           :: OperatorTimestep
  REAL(dp)           :: Hstart
  REAL(dp)           :: Hexit
  REAL(dp)           :: cosSZA
  REAL(dp)           :: TIN
  REAL(dp)           :: TOUT
  REAL(dp)           :: start
  REAL(dp)           :: end

  ! Arrays
  INTEGER            :: ICNTRL(20)
  INTEGER            :: ISTATUS(20)
  REAL(dp)           :: RCNTRL(20)
  REAL(dp)           :: RSTATE(20)
  REAL(dp)           :: Cinit(NSPEC)
  REAL(dp)           :: R(NREACT)


  ! Vars for reading files
  CHARACTER(LEN=256) :: inputFile
  CHARACTER(LEN=256) :: outputFile
  CHARACTER(LEN=256) :: toleranceFile

  ! Count the number of command-line arguments
  nArgs = Command_Argument_Count()

  ! Exit if no arguments were passed
  IF ( nArgs < 1 ) THEN
     PRINT*, 'No sample provided. Exiting.'
     STOP
  ENDIF

  ! The first argument is the input file containing model state
  ! archived from a previous GEOS-Chem simulation
  IF ( nArgs >= 1 ) THEN
     CALL Get_Command_Argument( 1, inputFile )
     PRINT*, 'Processing sample: ', TRIM( inputFile )
  ENDIF

  ! If a second argument is provided, use it as the output file
  IF ( nArgs >= 2 ) THEN
     CALL Get_Command_Argument( 2, outputFile )
     PRINT*, 'Output file: ', TRIM( outputFile )
  ENDIF

  ! Initialize
  RCONST = 0.0_dp
  C      = 0.0_dp

  ! Read the input file
  CALL Read_Input( inputfile,    R,                Cinit,  SPC_NAMES,        &
                   Hstart,       Hexit,            cosSZA, level,            &
                   fileTotSteps, OperatorTimestep, ICNTRL, RCNTRL,           &
                   ATOL                                                     )

  ! Run the full mechanism
  ! TODO: Pass RTOL from the commmand line
  CALL FullMech( RTOL_VALUE = 0.5e-2_dp )

  ! If an output file (2nd arg) was specified, write the results there
  IF ( nArgs >= 2 ) THEN
    CALL WriteOutput( inputFile, outputFile )
  ENDIF

  ! If a 3rd argument was specified, do a parameter exploration
  ! of tolerances and write output to the specified file
  IF ( nArgs >= 3 ) THEN
     CALL Get_Command_Argument( 3, toleranceFile )
     PRINT*, ""
     PRINT*, "Tolerance exploration file : ", trim( toleranceFile )
     CALL ToleranceLoop( toleranceFile )
  ENDIF

CONTAINS

  ! TODO: Pass RTOL as vector
  SUBROUTINE FullMech( RTOL_VALUE )
    !
    ! Integrates the GEOS-Chem Chemical mechanism forward
    !
    USE GCKPP_INTEGRATOR
    USE GCKPP_RATES
    USE GCKPP_INITIALIZE
    USE GCKPP_GLOBAL

    ! Inputs
    REAL(dp), INTENT(IN) :: RTOL_VALUE    ! Relative tolerance

    ! Initialize
    IERR      = 0                        ! Reset error flag
    ISTATUS   = 0                        ! Integer outputs
    RSTATE    = 0.0_dp                   ! Floating-point outputs
    C         = Cinit                    ! Concentrations from input file
    RCONST    = R                        ! Rxn rates from input file
    TIN       = 0.0_dp                   ! Start of integration
    TOUT      = TIN + OperatorTimestep   ! End of integration

    ! For most integrators, RCNTRL(3) is the starting value of the
    ! integration step size, so override the initial setting with this.
    RCNTRL(3) = Hstart

    ! Absolute tolerance (ATOL):
    ! Set to a default value if not defined in the input file.
    WHERE( ATOL < 0.0_dp )
       ATOL = 1.0e-2_dp
    ENDWHERE

    ! Relative tolerance (RTOL)
    RTOL = RTOL_VALUE

    ! Integrate the mechanism for an operator timestep
    CALL CPU_Time( start )
    CALL Integrate( TIN, TOUT, ICNTRL, RCNTRL, ISTATUS, RSTATE, IERR )
    CALL CPU_Time( end )

    ! Write results
    WRITE( 6, 10 ) fileTotSteps
 10 FORMAT( " Number of internal timesteps (from 3D run): ", i5 )

    WRITE( 6, 11 ) ISTATUS(3)
 11 FORMAT( " Number of internal timesteps ( standalone): ", i5 )

    WRITE( 6, 12 ) Hexit
 12 FORMAT(  " Hexit (from 3D run): ", f10.2 )

    WRITE( 6, 13 ) RSTATE(2)
 13 FORMAT( " Hexit ( standalone): ", f10.2 )

    ! Check if 3D results are consistent with standalone
    IF ( fileTotSteps /= ISTATUS(3) ) then
       WRITE( 6, 14 )
 14    FORMAT( "Warning: Number of internal steps do not match 3D grid cell" )
    ENDIF
    IF ( ABS( Hexit - RSTATE(2) ) / Hexit > 0.001_dp ) THEN
       WRITE( 6, 15 )
 15 FORMAT( "Warning: final timestep does not match 3D grid cell within 0.1%" )
    ENDIF

  END SUBROUTINE FullMech

  SUBROUTINE WriteOutput( inputFile, outputFile )
    !
    ! Writes initial and updated concentrations to a log file
    ! along with associated metadata
    !
    CHARACTER(len=256) :: outputfile
    CHARACTER(len=256) :: inputfile
    CHARACTER(len=256) :: header(30)
    INTEGER            :: i
    INTEGER            :: ierr
    CHARACTER(len=256) :: line

    ! Write meteo data lines of the input to the output file
    OPEN(20, file=outputfile)
    OPEN(10, file=inputfile, status='old')

    ! Write the header lines to the output file
    WRITE(20, '(A)') "43"
    WRITE(20, '(A)') REPEAT( "=", 79 )
    WRITE(20, '(A)') ""
    WRITE(20, '(A)') "KPP Standalone Output"
    WRITE(20, '(A)') "This file contains the concentrations of all the chemical species"
    WRITE(20, '(A)') "in a single grid cell of a GEOS-Chem 3D run as replicated by the "
    WRITE(20, '(A)') "KPP Standalone. Concentrations before and after the operator timestep"
    WRITE(20, '(A)') "are in CSV format, below."
    WRITE(20, '(A)') ""
    WRITE(20, '(A)') "Generated by the GEOS-Chem KPP Standalone:"
    WRITE(20, '(A)') "https://github.com/KineticPreProcessor/KPP-Standalone"
    WRITE(20, '(A)') ""
    WRITE(20, '(A)') "Input file used: " // trim(inputfile)
    WRITE(20, '(A)')

    ! Skip until we get to the metadata section
    DO
       READ( 10, '(A)', iostat=ierr ) line
       IF ( ierr /= 0 ) EXIT
       IF ( INDEX( line, 'Meteorological and general' ) > 0 ) THEN
          WRITE(20, '(A)') trim(line)
          EXIT
       ENDIF
    ENDDO

    ! Copy the metadata from the input file to the output file
    DO
       READ( 10, '(A)', iostat=ierr ) line
       IF ( ierr /= 0 ) EXIT
       IF ( INDEX( line, 'CSV data of full chemical state' ) > 0 ) EXIT
       WRITE( 20, '(A)' ) TRIM(line)
    ENDDO

    ! Close input file
    close(10)

    ! Write initial & final data to output file
    WRITE(20, '(A)') REPEAT( "=", 79 )
    WRITE(20, '(A)') "Species Name,Initial Concentration (molec/cm3),Final Concentration (molec/cm3)"
    ! write the species names, initial and final concentrations
    DO i=1,NSPEC
       WRITE(20, '(A, ES25.16E3, A, ES25.16E3)') &
          TRIM(SPC_NAMES(i)) // ",", Cinit(i), ",", C(i)
    ENDDO
    CLOSE(20)

  END SUBROUTINE WriteOutput

  SUBROUTINE ToleranceLoop( toleranceFile )
    !
    ! Performs a parameter exploration with different values of absolute
    ! and relative tolerances and writes results to a log file
    !
    USE GCKPP_INTEGRATOR
    USE GCKPP_RATES
    USE GCKPP_INITIALIZE
    USE GCKPP_GLOBAL

    ! Input arguments
    CHARACTER(LEN=*), INTENT(IN) :: tolerancefile

    ! Local variables
    INTEGER            :: NA, NR, combo
    INTEGER, PARAMETER :: ILUN = 30
    REAL(dp)           :: tolerances(16) = (/                                &
                            0.75_dp,    0.5_dp,    0.25_dp,    0.1_dp,       &
                            0.075_dp,   0.05_dp,   0.025_dp,   0.01_dp,      &
                            0.0075_dp,  0.005_dp,  0.0025_dp,  0.001_dp,     &
                            0.00075_dp, 0.0005_dp, 0.00025_dp, 0.0001_dp   /)

    ! Initialize
    combo     = 0                  ! Combination number
    IERR      = 0                  ! Zero error flag
    ISTATUS   = 0                  ! Zero integer outputs
    RSTATE    = 0.0_dp             ! Zero floating-point outputs
    RCNTRL(3) = OperatorTimestep   ! Starting timestep for integration

    ! Absolute tolerance (ATOL):
    ! Set missing values to a default value
    WHERE( ATOL < 0.0_dp )
       ATOL = 1.0e-2_dp
    ENDWHERE

    ! Open file for output
    OPEN( ILUN, FILE=tolerancefile )

    ! Loop over absolute tolerances
    DO NA = 1, SIZE( tolerances )

       ! Assign absolute tolerances
       ! Skip prod/loss species with high absolute tolerances
       WHERE( ATOL < 1.0e25 )
          ATOL = tolerances(NA)
       ENDWHERE

       ! Loop over relative tolerances
       DO NR = 1, SIZE( tolerances )

          ! Combination number
          combo  = combo + 1

          ! Assign relative tolerance
          RTOL   = tolerances(NR)

          ! Prepare for the integration
          C      = Cinit                    ! Concentrations from input file
          RCONST = R                        ! Rxn rates from input file
          TIN    = 0.0_dp                   ! Start of integration
          TOUT   = TIN + OperatorTimestep   ! End of integration

          ! Integrate the mechanism for an operator timestep
          CALL CPU_Time( start )
          CALL Integrate( TIN, TOUT, ICNTRL, RCNTRL, ISTATUS, RSTATE, IERR )
          CALL CPU_Time( end )

          ! Write results
          WRITE( ILUN, 50  ) combo, REPEAT( "<", 50 )
  50      FORMAT( ">>>>>>>> Combination ", i4, 1x, a )

          WRITE( ILUN, 100  ) ATOL(1)
 100      FORMAT( ' ATOL                                     : ', es11.4 )

          WRITE( ILUN, 110  ) RTOL(1)
 110      FORMAT( ' RTOL                                     : ', es11.4 )

          IF ( IERR < 0 ) THEN
             WRITE( 6, 115 ) IERR
 115         FORMAT( " Integration returned with error code     : ", i8  )
             CYCLE
          ENDIF

          WRITE( ILUN, 120 ) ISTATUS(1)
 120      FORMAT( " Number of times function F was computed  : ", i8     )

          WRITE( ILUN, 130 ) ISTATUS(2)
 130      FORMAT( " Number of times Jacobian was computed    : ", i8     )

          WRITE( ILUN, 140 ) ISTATUS(3)
 140      FORMAT( " Number of internal timesteps             : ", i8     )

          WRITE( ILUN, 150 ) ISTATUS(4)
 150      FORMAT( " --> Accepted timesteps                   : ", i8     )

          WRITE( ILUN, 160 ) ISTATUS(5)
 160      FORMAT( " --> Rejected timesteps                   : ", i8     )

          WRITE( ILUN, 170 ) ISTATUS(6)
 170      FORMAT( " Number of LU decompositions performed    : ", i8     )

          WRITE( ILUN, 180 ) ISTATUS(7)
 180      FORMAT( " Number of forward/backward substitutions : ", i8     )

          WRITE( ILUN, 190 ) RSTATE(1)
 190      FORMAT( " Texit (time corresponding to computed Y) : ", f13.6  )

          WRITE( ILUN, 200 ) RSTATE(2)
 200      FORMAT( " Hexit (last accepted step before exit)   : ", f13.6  )

          WRITE( ILUN, 210 ) RSTATE(3)
 210      FORMAT( " Hnew (last predicted step not yet taken) : ", f13.6  )

          WRITE( ILUN, 220 ) end - start
 220      FORMAT( " Wall clock time                          : ", f13.6  )

       ENDDO
    ENDDO

    ! Close file
    CLOSE( ILUN )

  END SUBROUTINE ToleranceLoop

END PROGRAM Main
